### ISSUE TITLE
Investigate the issue that remains mon with replicas=0 on stage0 ceph-ssd

### ISSUE THREAD

**Issue by cupnes** [cybozu/csa#101]
## Objective

Investigate the issue that remains mon with replicas=0.

## How

- [x] Check `kubectl get deployments` with `managedFields`.
- [ ] Check other mon's deployment information.
- etc

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
We have no such mon anymore. This is a low priority.
