### ISSUE TITLE
Migrate CSA overview dashboard to csa-apps repo

### ISSUE THREAD

**Issue by llamerada-jp** [cybozu/csa#107]
## Objective

Migrate CSA overview dashboard to csa-apps repo
- Test of neco-apps consumes a lot of time but it can't check dashboard.

## How

- code of maneki-apps may be helpful.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
https://github.com/cybozu-private/neco-apps/pull/2804
