### ISSUE TITLE
Set syncPolicy.syncOptions.RespectIgnoreDifferences=true if necessary

### ISSUE THREAD

**Issue by daichimukai** [cybozu/csa#109]
## Objective

From Argo CD v2.3.0, `syncPolicy.syncOptions.RespectIgnoreDifferences=true` is supported. This sync option ignores difference sync stage too.
Set this option if necessary to avoid sync troubles.

## How

Set sync option to rook and logging-small.

https://github.com/cybozu-go/neco-apps/blob/d82ec52bc472f462eab561bd3b63ee08c3c52acd/argocd-config/base/rook.yaml#L28-L33
https://github.com/cybozu-go/neco-apps/blob/d82ec52bc472f462eab561bd3b63ee08c3c52acd/argocd-config/base/logging-small.yaml#L24-L31

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
https://github.com/cybozu-private/neco-apps/pull/2678
