### ISSUE TITLE
enable RespectIgnoreDifferences in ArgoCD application

### ISSUE THREAD

**Issue by daichimukai** [cybozu/csa#113]
## Objective

To avoid sync error, set RespectIgnoreDifferences=true for argocd sync policy.

## How

Set RespectIgnoreDifferences=true for argocd sync policy for logging-small, rook, etc.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
duplicate of #109
