### ISSUE TITLE
Monitor if services have matched pods

### ISSUE THREAD

**Issue by toshipp** [cybozu/csa#119]
## Objective

When we updated TopoLVM, the update changed label selectors which are immutable fields on Daemonsets and Deployments, ArgoCD could not apply the manifests. The service is also changed to use new matching labels, however, it is mutable, so ArgoCD did apply it. Therefore, the service that had no matched pods appeared.
In other cases, such as misconfiguration, it is also useful to monitor the case.

## How

- TBD (kube-state-metrics may expose useful metrics)
  - `kube_endpoint_address_available` looks useful for this issue. Normally, endpoint resource will be created when svc resource exists.
- set severity warn? (misconfiguration may not be critical, and other monitors can check related incidents if they are critical)

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by daichimukai** [comment]
The real problem is that "service does not respond". e2e test would be more appropriate.

**Comment by daichimukai** [comment]
- TopoLVM webhook is covered in #118
- RBD and RGW will be covered in #6
