### ISSUE TITLE
Rook/Ceph: apply priorityClass for CrashCollector

### ISSUE THREAD

**Issue by toshipp** [cybozu/csa#17]
## What

CrashCollector need higher priority to schedule in preference to other pods.

## How

need patch for Rook upstream to set priorityClass for CrashCollector pod.
- https://rook.io/docs/rook/v1.5/ceph-cluster-crd.html#priority-class-names-configuration-settings
- https://bozuman.cybozu.com/k/#/space/3801/thread/27736/2744997/4472334

## Checklist

- [x] Finish implementation of the issue
- [x] apply this feature into neco-apps
- [x] Test all functions
- [ ] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by satoru-takeuchi** [comment]
Rook's issue
https://github.com/rook/rook/issues/9500

PR
https://github.com/rook/rook/pull/9502

**Comment by satoru-takeuchi** [comment]
PR was merged and was backpored to v1.8 branch.

https://github.com/rook/rook/pull/9502
