### ISSUE TITLE
Mitigate health warn for reporting "not scrubbed in time"

### ISSUE THREAD

**Issue by toshipp** [cybozu/csa#69]
## Objective

Sometimes, ceph cluster reports "not deep-scrubbed in time" and sets its status to HEALTH_WARN.
It seems harmless, so mitigate this situation.

## How

- possibly, reconfigure some configuration.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by peng225** [comment]
Currently, we are not suffering from this warning. So we should leave it as it is.
