### ISSUE TITLE
ceph: Reduce the delay in voluntary OSD shutdown

### ISSUE THREAD

**Issue by satoru-takeuchi** [cybozu/csa#76]
## Objective

When voluntary OSD shutdown, OSD doesn't notify mon. It causes the following slow ops.
https://tracker.ceph.com/issues/46978

This problem can be resolved by enabling `osd_shutdown_notify_mon`  option. This option would also reduce the long I/O delay just after the voluntary OSD shutdown written in our wiki.

> research_ceph_osd_down_detenction.html#考察

TODO:
The following problems should be resolved before enabling this option.

https://tracker.ceph.com/issues/53327
https://tracker.ceph.com/issues/53266

See also.

> k/#/space/6740/thread/50300/3148086/5826560
## How

- Set `osd_shutdown_notify_mon` option in `rook-ceph-override` configmap in all ceph clusters.
- Check if IO stop duration will be shortened when osd shutdown

## Checklist

- [x] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
pacific backport: https://github.com/ceph/ceph/pull/45654
