### ISSUE TITLE
Add dashboard to view metrics using VM-largeset

### ISSUE THREAD

**Issue by llamerada-jp** [cybozu/csa#77]
## Objective

A dashboard using VM-largeset will also be provided to ensure availability.
Dashboards for Rook/Ceph is using VM-smallset as the data source. And it isn't able to use when VM-smallset pods are restarting. 

## How

It would be nice to switch data sources. Otherwise, add a new dashboard that only the data source is different.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
closed via https://github.com/cybozu-go/neco-apps/pull/2311
