### ISSUE TITLE
Possess the know-how to investigate slow ops

### ISSUE THREAD

**Issue by llamerada-jp** [cybozu/csa#85]
## Objective

In order to resolve slow ops in OSD, we should have the know-how to investigate the root cause. In this task, we will research and document methods for investigating causes.

## How

- Looking for usable metrics and commands to investigate.

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by toshipp** [comment]
In #106, The slow request turned out to be caused by poor use of rocksdb. Close as there does not seem to be a generic method in the survey.
