### ISSUE TITLE
[Rook/Ceph][2022/07] update rook and ceph

### ISSUE THREAD

**Issue by llamerada-jp** [cybozu/csa#96]
## Objective
Update rook and ceph to the latest version.

## How

- update rook and ceph
- add sst_dump (provided by rocksdb) or other rocksdb debug tools
- if use Ceph v17, add CephBlockBool CR for `.mgr` should be added. 
- Set device class appropriately to enable pg auto-scaler (#99 )
- use golang:1.17-focal or higher as a build container.

## Checklist

- [ ] Add "add CephBlockBool CR for `.mgr` should be added. " to the TODO of the next Rook/Ceph upgrade.
- [x] add sst_dump (provided by rocksdb) or other rocksdb debug tools
- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions
- [ ] Revert #100 after updating ceph in prod, See [here](https://github.com/cybozu/csa/issues/96#issuecomment-1155868719)

**Comment by toshipp** [comment]
#106: rgw slow request issue is resolved as of 16.2.8 (but it has some regressions)
It is time to revert #100.
